apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  
spec:

  selector:
    matchLabels:
      app: my-sqlkanika
  template:
    metadata:
      labels:
        app: my-sqlkanika
    spec:
      containers:
      - name: configdeployment
        image: mysql:5.6
        ports:
        - containerPort: 3306
        env:
        - name : MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
               name: mysecret 
               key: password